### ISSUE TITLE
Expand the functionality for private github domains

### ISSUE THREAD

**Issue by SDSethia** [fabiocchetti/widegithub#1]
Provide plugin options to expand the functionality for private github domains
eg: github.some_company.com

**Comment by rredburn** [comment]
@fabiocchetti  perhaps just a simple change like this is sufficient for everyone (?)

`"matches": ["*://github*.com/*"],`

**Comment by LunaticoCR** [comment]
> "matches": ["*://github*.com/*"],

This wouldn't work in my case actually... It would have to be something like:
```
"matches": ["*://*github*.com/*"],
```

**Comment by fabiocchetti** [comment]
Thanks for your suggestions.

It should be fixed on version 1.1.0.

Since I don't have access to any private GitHub domain, I've been unable to test it. Please file a new issue if it's still not working as expected.

**Comment by fregante** [comment]
@fabiocchetti that won't work because the extension doesn't have permission to access those domains. You'd need `optional_permissions`, a way to request permissions by the user, and a way to dynamically inject the scripts.

I wrote two modules to help you with that, the implementation is rather simple: https://github.com/fregante/webext-dynamic-content-scripts

**Comment by fabiocchetti** [comment]
Hello @fregante, thanks for sharing this. It's really interesting and I'll look into it in the future.
